# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-07 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LipopeptideApplicationsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lipopeptide_application', models.TextField()),
                ('application_description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 21, 49, 294918, tzinfo=utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LipopeptideData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lipopeptide_name', models.CharField(max_length=255)),
                ('lipopeptide_organism', models.TextField()),
                ('lipopeptide_family', models.CharField(max_length=255)),
                ('lipopeptide_structure_3d', models.ImageField(upload_to=b'')),
                ('lipopeptide_primary_sequence', models.TextField()),
                ('lipopeptide_secondary_sequence', models.TextField()),
                ('lipopeptide_tertiary_sequence', models.TextField()),
                ('lipopeptide_source', models.TextField()),
                ('lipopeptide_summary', models.TextField()),
                ('lipopeptide_activity', models.TextField()),
                ('molecular_formula', models.CharField(max_length=100)),
                ('molecular_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lipopeptide_structure_2d', models.ImageField(upload_to=b'')),
                ('canonical_smiles', models.TextField()),
                ('cas_number', models.IntegerField()),
                ('ec_number', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 21, 49, 293771, tzinfo=utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LipopeptideDiscoverData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discoverer_name', models.CharField(max_length=255)),
                ('discoverer_profile', models.URLField()),
                ('discoverer_introduction', models.TextField()),
                ('discoverer_image', models.ImageField(upload_to=b'')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 21, 49, 299831, tzinfo=utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lipopeptide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.LipopeptideData')),
            ],
        ),
        migrations.CreateModel(
            name='LipopeptideFunctionsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lipopeptide_function', models.TextField()),
                ('function_description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 21, 49, 297320, tzinfo=utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lipopeptide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.LipopeptideData')),
            ],
        ),
        migrations.CreateModel(
            name='LipopeptideLigandData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligand_name', models.CharField(max_length=255)),
                ('ligand_position', models.CharField(max_length=255)),
                ('is_already_bound', models.BooleanField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 21, 49, 298126, tzinfo=utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lipopeptide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.LipopeptideData')),
            ],
        ),
        migrations.CreateModel(
            name='LipopeptideMetabolismData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lipopeptide_metabolism_stage', models.CharField(max_length=255)),
                ('metabolism_description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 21, 49, 300908, tzinfo=utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lipopeptide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.LipopeptideData')),
            ],
        ),
        migrations.CreateModel(
            name='LipopeptidePathwayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lipopeptide_pathway_name', models.CharField(max_length=255)),
                ('lipopeptide_pathway_description', models.TextField()),
                ('lipopeptide_pathway_image', models.ImageField(upload_to=b'')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 21, 49, 298919, tzinfo=utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lipopeptide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.LipopeptideData')),
            ],
        ),
        migrations.CreateModel(
            name='LipopeptidePropertiesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.IntegerField(choices=[(1, 'Physical'), (2, 'Chemical')])),
                ('property_description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 21, 49, 301677, tzinfo=utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lipopeptide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.LipopeptideData')),
            ],
        ),
        migrations.CreateModel(
            name='LipopeptideReferencesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_data', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 21, 49, 302398, tzinfo=utc))),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lipopeptide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.LipopeptideData')),
            ],
        ),
        migrations.AddField(
            model_name='lipopeptideapplicationsdata',
            name='lipopeptide_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteins.LipopeptideData'),
        ),
    ]
