# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-07 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0002_auto_20200207_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipopeptideapplicationsdata',
            name='application_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptideapplicationsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 59, 41, 543680, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptideapplicationsdata',
            name='lipopeptide_application',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='canonical_smiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='cas_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 59, 41, 542618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='ec_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_organism',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_primary_sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_secondary_sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_structure_2d',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_structure_3d',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='lipopeptide_tertiary_sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='molecular_formula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='molecular_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidediscoverdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 59, 41, 548919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidediscoverdata',
            name='discoverer_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='lipopeptidediscoverdata',
            name='discoverer_introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidediscoverdata',
            name='discoverer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidediscoverdata',
            name='discoverer_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidefunctionsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 59, 41, 546233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidefunctionsdata',
            name='function_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidefunctionsdata',
            name='lipopeptide_function',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptideliganddata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 59, 41, 547089, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptideliganddata',
            name='ligand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptideliganddata',
            name='ligand_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidemetabolismdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 59, 41, 549958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidemetabolismdata',
            name='lipopeptide_metabolism_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidemetabolismdata',
            name='metabolism_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidepathwaydata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 59, 41, 547909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidepathwaydata',
            name='lipopeptide_pathway_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidepathwaydata',
            name='lipopeptide_pathway_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='lipopeptidepathwaydata',
            name='lipopeptide_pathway_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidepropertiesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 59, 41, 550743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidepropertiesdata',
            name='property_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidepropertiesdata',
            name='property_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Physical'), (2, 'Chemical')], null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidereferencesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 7, 8, 59, 41, 551484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidereferencesdata',
            name='reference_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
