# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-02 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0008_auto_20200228_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lipopeptidedata',
            name='lipopeptide_family',
        ),
        migrations.RemoveField(
            model_name='lipopeptidedata',
            name='lipopeptide_primary_sequence',
        ),
        migrations.RemoveField(
            model_name='lipopeptidedata',
            name='lipopeptide_secondary_sequence',
        ),
        migrations.RemoveField(
            model_name='lipopeptidedata',
            name='lipopeptide_source',
        ),
        migrations.RemoveField(
            model_name='lipopeptidedata',
            name='lipopeptide_structure_3d',
        ),
        migrations.RemoveField(
            model_name='lipopeptidedata',
            name='lipopeptide_tertiary_sequence',
        ),
        migrations.RemoveField(
            model_name='lipopeptidefunctionsdata',
            name='function_description',
        ),
        migrations.AlterField(
            model_name='lipopeptideapplicationsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 33, 28, 844024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 33, 28, 843236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidediscoverdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 33, 28, 848294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidefunctionsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 33, 28, 846027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptideliganddata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 33, 28, 846771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidemetabolismdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 33, 28, 849368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidepathwaydata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 33, 28, 847472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidepropertiesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 33, 28, 850122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidereferencesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 33, 28, 850787, tzinfo=utc)),
        ),
    ]
