# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-02 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0009_auto_20200302_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lipopeptidediscoverdata',
            name='lipopeptide_id',
        ),
        migrations.RemoveField(
            model_name='lipopeptidepathwaydata',
            name='lipopeptide_id',
        ),
        migrations.RemoveField(
            model_name='lipopeptideapplicationsdata',
            name='application_description',
        ),
        migrations.AlterField(
            model_name='lipopeptideapplicationsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 36, 18, 839273, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 36, 18, 838515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidefunctionsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 36, 18, 841239, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptideliganddata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 36, 18, 841967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidemetabolismdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 36, 18, 842722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidepropertiesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 36, 18, 843502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidereferencesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 8, 36, 18, 844162, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='LipopeptideDiscoverData',
        ),
        migrations.DeleteModel(
            name='LipopeptidePathwayData',
        ),
    ]
