# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-10 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0010_auto_20200302_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lipopeptidepropertiesdata',
            name='property_description',
        ),
        migrations.RemoveField(
            model_name='lipopeptidepropertiesdata',
            name='property_type',
        ),
        migrations.AddField(
            model_name='lipopeptidepropertiesdata',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptideapplicationsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 11, 52, 52, 267345, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 11, 52, 52, 266462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidefunctionsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 11, 52, 52, 269543, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptideliganddata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 11, 52, 52, 270331, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidemetabolismdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 11, 52, 52, 271210, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidepropertiesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 11, 52, 52, 272343, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidepropertiesdata',
            name='property_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptidereferencesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 11, 52, 52, 273105, tzinfo=utc)),
        ),
    ]
