# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-06 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0011_auto_20200310_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipopeptideapplicationsdata',
            name='application_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lipopeptideapplicationsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 21, 26, 12, 215243, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 21, 26, 12, 213655, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidefunctionsdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 21, 26, 12, 218259, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptideliganddata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 21, 26, 12, 219529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidemetabolismdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 21, 26, 12, 221120, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidepropertiesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 21, 26, 12, 222667, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lipopeptidereferencesdata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 21, 26, 12, 232064, tzinfo=utc)),
        ),
    ]
